# spring
spring:
  application:
    name: sky-common

  # redis
  redis:
    # Redis服务器地址
    host: 47.100.183.36
    # Redis服务器连接端口
    port: 6379
    # 密码
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

# 日志
logging:
  level:
    root: DEBUG
  config: classpath:log/logback-spring-dev.xml
